import { GanttTask, GanttDependency } from './types';

export const MOCK_TASKS: GanttTask[] = [
  {
    id: '1',
    name: 'Project Kickoff',
    type: 'summary',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-01-31'),
    duration: 20,
    progress: 50,
    parentId: null,
    children: ['2', '3'],
    level: 0,
    expanded: true,
    color: '#3b82f6',
  },
  {
    id: '2',
    name: 'Requirements Gathering',
    type: 'task',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-01-10'),
    duration: 7,
    progress: 100,
    parentId: '1',
    level: 1,
    expanded: false,
    color: '#10b981',
  },
  {
    id: '3',
    name: 'Design Phase',
    type: 'task',
    startDate: new Date('2024-01-11'),
    endDate: new Date('2024-01-25'),
    duration: 10,
    progress: 60,
    parentId: '1',
    level: 1,
    expanded: false,
    color: '#8b5cf6',
  },
  {
    id: '4',
    name: 'Development Sprint 1',
    type: 'summary',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-02-29'),
    duration: 20,
    progress: 30,
    parentId: null,
    children: ['5', '6'],
    level: 0,
    expanded: true,
    color: '#f59e0b',
  },
  {
    id: '5',
    name: 'Backend API',
    type: 'task',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-02-15'),
    duration: 10,
    progress: 40,
    parentId: '4',
    level: 1,
    expanded: false,
    color: '#06b6d4',
  },
  {
    id: '6',
    name: 'Frontend UI',
    type: 'task',
    startDate: new Date('2024-02-16'),
    endDate: new Date('2024-02-29'),
    duration: 10,
    progress: 20,
    parentId: '4',
    level: 1,
    expanded: false,
    color: '#ec4899',
  },
  {
    id: '7',
    name: 'Testing & QA',
    type: 'task',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-03-15'),
    duration: 10,
    progress: 0,
    parentId: null,
    level: 0,
    expanded: false,
    color: '#ef4444',
  },
  {
    id: '8',
    name: 'Launch Milestone',
    type: 'milestone',
    startDate: new Date('2024-03-20'),
    endDate: new Date('2024-03-20'),
    duration: 0,
    progress: 0,
    parentId: null,
    level: 0,
    expanded: false,
    color: '#14b8a6',
  },
];

export const MOCK_DEPENDENCIES: GanttDependency[] = [
  { id: 'd1', fromTaskId: '2', toTaskId: '3', type: 'FS', lag: 0 },
  { id: 'd2', fromTaskId: '3', toTaskId: '5', type: 'FS', lag: 0 },
  { id: 'd3', fromTaskId: '5', toTaskId: '6', type: 'FS', lag: 0 },
  { id: 'd4', fromTaskId: '6', toTaskId: '7', type: 'FS', lag: 0 },
  { id: 'd5', fromTaskId: '7', toTaskId: '8', type: 'FS', lag: 0 },
];
