import { Resource, SchedulerEvent, Dependency } from '../core/types';
import { addDays, addHours, startOfDay } from './dateUtils';

export function generateSampleResources(): Resource[] {
  return [
    {
      id: 'team-1',
      name: 'Engineering Team',
      type: 'Team',
      color: '#3b82f6',
      expanded: true,
      children: [
        {
          id: 'dev-1',
          name: 'Alice Johnson',
          type: 'Senior Developer',
          color: '#8b5cf6',
          parentId: 'team-1',
        },
        {
          id: 'dev-2',
          name: 'Bob Smith',
          type: 'Full Stack Developer',
          color: '#06b6d4',
          parentId: 'team-1',
        },
        {
          id: 'dev-3',
          name: 'Carol Williams',
          type: 'Frontend Developer',
          color: '#10b981',
          parentId: 'team-1',
        },
      ],
    },
    {
      id: 'team-2',
      name: 'Design Team',
      type: 'Team',
      color: '#f59e0b',
      expanded: true,
      children: [
        {
          id: 'des-1',
          name: 'David Brown',
          type: 'UI Designer',
          color: '#ec4899',
          parentId: 'team-2',
        },
        {
          id: 'des-2',
          name: 'Emma Davis',
          type: 'UX Researcher',
          color: '#f43f5e',
          parentId: 'team-2',
        },
      ],
    },
    {
      id: 'team-3',
      name: 'Product Team',
      type: 'Team',
      color: '#14b8a6',
      expanded: true,
      children: [
        {
          id: 'pm-1',
          name: 'Frank Miller',
          type: 'Product Manager',
          color: '#8b5cf6',
          parentId: 'team-3',
        },
        {
          id: 'pm-2',
          name: 'Grace Lee',
          type: 'Product Owner',
          color: '#6366f1',
          parentId: 'team-3',
        },
      ],
    },
    {
      id: 'team-4',
      name: 'Marketing Team',
      type: 'Team',
      color: '#ef4444',
      expanded: false,
      children: [
        {
          id: 'mkt-1',
          name: 'Henry Wilson',
          type: 'Marketing Manager',
          color: '#f97316',
          parentId: 'team-4',
        },
        {
          id: 'mkt-2',
          name: 'Iris Taylor',
          type: 'Content Strategist',
          color: '#eab308',
          parentId: 'team-4',
        },
      ],
    },
  ];
}

export function generateSampleEvents(): SchedulerEvent[] {
  const today = startOfDay(new Date());

  return [
    // Week 1
    {
      id: 'evt-1',
      resourceId: 'dev-1',
      title: 'Authentication System',
      description: 'Implement OAuth 2.0 authentication',
      startDate: addDays(today, 0),
      endDate: addDays(today, 3),
      status: 'in-progress',
      priority: 'high',
      color: '#8b5cf6',
      progress: 65,
      draggable: true,
      resizable: true,
      editable: true,
    },
    {
      id: 'evt-2',
      resourceId: 'dev-2',
      title: 'API Integration',
      description: 'Connect to third-party payment API',
      startDate: addDays(today, 1),
      endDate: addDays(today, 4),
      status: 'scheduled',
      priority: 'medium',
      color: '#06b6d4',
      progress: 30,
      draggable: true,
      resizable: true,
      editable: true,
    },
    {
      id: 'evt-3',
      resourceId: 'dev-3',
      title: 'Dashboard UI',
      description: 'Build responsive dashboard interface',
      startDate: addDays(today, 2),
      endDate: addDays(today, 5),
      status: 'in-progress',
      priority: 'high',
      color: '#10b981',
      progress: 45,
      draggable: true,
      resizable: true,
      editable: true,
    },

    // Week 2
    {
      id: 'evt-4',
      resourceId: 'dev-1',
      title: 'Database Migration',
      description: 'Migrate from MySQL to PostgreSQL',
      startDate: addDays(today, 4),
      endDate: addDays(today, 7),
      status: 'scheduled',
      priority: 'urgent',
      color: '#8b5cf6',
      progress: 0,
      draggable: true,
      resizable: true,
      editable: true,
    },
    {
      id: 'evt-5',
      resourceId: 'dev-2',
      title: 'Performance Optimization',
      description: 'Optimize database queries and caching',
      startDate: addDays(today, 5),
      endDate: addDays(today, 8),
      status: 'scheduled',
      priority: 'medium',
      color: '#06b6d4',
      progress: 0,
      draggable: true,
      resizable: true,
      editable: true,
    },
    {
      id: 'evt-6',
      resourceId: 'dev-3',
      title: 'Mobile Responsiveness',
      description: 'Ensure all pages work on mobile devices',
      startDate: addDays(today, 6),
      endDate: addDays(today, 9),
      status: 'scheduled',
      priority: 'high',
      color: '#10b981',
      progress: 0,
      draggable: true,
      resizable: true,
      editable: true,
    },

    // Design Team
    {
      id: 'evt-7',
      resourceId: 'des-1',
      title: 'Design System',
      description: 'Create comprehensive design system',
      startDate: addDays(today, -2),
      endDate: addDays(today, 3),
      status: 'in-progress',
      priority: 'high',
      color: '#ec4899',
      progress: 80,
      draggable: true,
      resizable: true,
      editable: true,
    },
    {
      id: 'evt-8',
      resourceId: 'des-2',
      title: 'User Testing',
      description: 'Conduct usability testing sessions',
      startDate: addDays(today, 1),
      endDate: addDays(today, 2),
      status: 'scheduled',
      priority: 'medium',
      color: '#f43f5e',
      progress: 0,
      draggable: true,
      resizable: true,
      editable: true,
    },
    {
      id: 'evt-9',
      resourceId: 'des-1',
      title: 'Prototype Review',
      description: 'Review and iterate on prototypes',
      startDate: addDays(today, 4),
      endDate: addDays(today, 6),
      status: 'scheduled',
      priority: 'medium',
      color: '#ec4899',
      progress: 0,
      draggable: true,
      resizable: true,
      editable: true,
    },

    // Product Team
    {
      id: 'evt-10',
      resourceId: 'pm-1',
      title: 'Sprint Planning',
      description: 'Plan next sprint deliverables',
      startDate: addDays(today, 0),
      endDate: addDays(today, 1),
      status: 'completed',
      priority: 'high',
      color: '#8b5cf6',
      progress: 100,
      draggable: true,
      resizable: true,
      editable: true,
    },
    {
      id: 'evt-11',
      resourceId: 'pm-2',
      title: 'Stakeholder Meeting',
      description: 'Present Q4 roadmap to stakeholders',
      startDate: addDays(today, 2),
      endDate: addDays(today, 2),
      status: 'scheduled',
      priority: 'urgent',
      color: '#6366f1',
      progress: 0,
      draggable: true,
      resizable: true,
      editable: true,
    },
    {
      id: 'evt-12',
      resourceId: 'pm-1',
      title: 'Feature Prioritization',
      description: 'Prioritize features for next quarter',
      startDate: addDays(today, 7),
      endDate: addDays(today, 8),
      status: 'scheduled',
      priority: 'medium',
      color: '#8b5cf6',
      progress: 0,
      draggable: true,
      resizable: true,
      editable: true,
    },

    // Marketing Team (collapsed, so won't show unless expanded)
    {
      id: 'evt-13',
      resourceId: 'mkt-1',
      title: 'Campaign Launch',
      description: 'Launch Q4 marketing campaign',
      startDate: addDays(today, 3),
      endDate: addDays(today, 10),
      status: 'scheduled',
      priority: 'high',
      color: '#f97316',
      progress: 0,
      draggable: true,
      resizable: true,
      editable: true,
    },
    {
      id: 'evt-14',
      resourceId: 'mkt-2',
      title: 'Content Creation',
      description: 'Create blog posts and social media content',
      startDate: addDays(today, 1),
      endDate: addDays(today, 7),
      status: 'in-progress',
      priority: 'medium',
      color: '#eab308',
      progress: 40,
      draggable: true,
      resizable: true,
      editable: true,
    },
  ];
}

export function generateSampleDependencies(): Dependency[] {
  return [
    {
      id: 'dep-1',
      fromEventId: 'evt-1',
      toEventId: 'evt-4',
      type: 'finish-to-start',
      lag: 0,
      color: '#3b82f6',
    },
    {
      id: 'dep-2',
      fromEventId: 'evt-2',
      toEventId: 'evt-5',
      type: 'finish-to-start',
      lag: 24,
      color: '#06b6d4',
    },
    {
      id: 'dep-3',
      fromEventId: 'evt-7',
      toEventId: 'evt-3',
      type: 'finish-to-start',
      lag: 0,
      color: '#ec4899',
    },
    {
      id: 'dep-4',
      fromEventId: 'evt-10',
      toEventId: 'evt-1',
      type: 'finish-to-start',
      lag: 0,
      color: '#8b5cf6',
    },
  ];
}
